name: Deploy Nodejs to VPS Docker with Zero Downtime

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy back end to VPS with Zero Downtime
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        # SSH vào VPS và triển khai
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          
          # Clone repository mới nếu chưa có, hoặc pull latest nếu đã có
          if [ ! -d "baemin_be" ]; then
            git clone https://github.com/khoidang2110/baemin_be.git
          fi
          cd baemin_be || exit
          
          # Pull latest code (nếu đã có repo)
          git reset --hard
          git pull

          # Build Docker image mới
          docker build -t bm_be .

          # Kiểm tra và quyết định cổng (Blue-Green deployment)
          if docker ps --filter "name=bm_nest_8096" --format "{{.Names}}" | grep -q "bm_nest_8096"; then
            TARGET_PORT=8097
            TARGET_NAME=bm_nest_8097
          else
            TARGET_PORT=8096
            TARGET_NAME=bm_nest_8096
          fi

          # Tạo container mới trên cổng xác định trước khi dừng container cũ
          docker run -e --restart=always -d -p $TARGET_PORT:8096 --name $TARGET_NAME bm_be

          # Đảm bảo container mới đã chạy trước khi dừng container cũ
          sleep 5

          # Dừng và xóa container cũ nếu tồn tại
          docker stop bm_nest_$(if [ $TARGET_PORT -eq 8096 ]; then echo "8097"; else echo "8096"; fi) || true
          docker rm bm_nest_$(if [ $TARGET_PORT -eq 8096 ]; then echo "8097"; else echo "8096"; fi) || true

          # Xóa các images cũ không còn sử dụng
          docker image prune -f

          # Xóa thư mục clone nếu không cần thiết nữa
          cd ..
          rm -rf baemin_be
        EOF
