name: Deploy Nodejs to VPS Docker with Zero Downtime

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy back end to VPS with Zero Downtime
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        # SSH vào VPS và triển khai
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          
          # Clone repository mới nếu chưa có, hoặc pull latest nếu đã có
          if [ ! -d "baemin_be" ]; then
            git clone https://github.com/khoidang2110/baemin_be.git
          fi
          cd baemin_be || exit
          
       

        

          # Kiểm tra xem container bm_nest_8096 đã chạy chưa
          if docker ps --filter "name=bm_nest_8096" --format "{{.Names}}" | grep -q "bm_nest_8096"; then
            # Nếu bm_nest_8096 đã chạy, ta sẽ tạo bm_nest_8097 từ image bm_be_8097
            TARGET_PORT=8097
            TARGET_NAME=bm_nest_8097
            IMAGE_NAME=bm_be_8097

            # Build image bm_be_8097 nếu chưa có
            docker build -t $IMAGE_NAME .
          else
            # Nếu bm_nest_8096 chưa chạy, ta sẽ tạo bm_nest_8096 từ image bm_be_8096
            TARGET_PORT=8096
            TARGET_NAME=bm_nest_8096
            IMAGE_NAME=bm_be_8096

            # Build image bm_be_8096 nếu chưa có
            docker build -t $IMAGE_NAME .
          fi

          # Tạo container mới trên cổng xác định
          docker run -e --restart=always -d -p $TARGET_PORT:8096 --name $TARGET_NAME $IMAGE_NAME
          
          # Đảm bảo container mới đã chạy trước khi dừng container cũ
          sleep 5

          # Dừng và xóa container cũ nếu tồn tại
          if [ "$TARGET_PORT" -eq 8097 ]; then
            docker stop bm_nest_8096 || true
            docker rm bm_nest_8096 || true
          else
            docker stop bm_nest_8097 || true
            docker rm bm_nest_8097 || true
          fi

          # Xóa các images cũ không còn sử dụng
          docker image prune -f

          # Xóa thư mục clone nếu không cần thiết nữa
          cd ..
          rm -rf baemin_be
        EOF
