name: Deploy Nodejs to VPS Docker v1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy back end to VPS
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
    
        
      run: |
        env
        
        # SSH into VPS to extract and deploy
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          echo ${{ secrets.VPS_IP }} >> tmpfile
         # Clone the repository 
          git clone https://github.com/khoidang2110/baemin_be.git
          cd baemin_be || exit
          docker stop bm_nest || true
          docker rm bm_nest || true
          docker rmi -f bm_be || true  
          docker build -t bm_be .
          # docker - d chạy nodejs ngầm ko chạy lên terminal
          docker run -e --restart=always -d -p 8096:8096 --name bm_nest bm_be
           # Clean up by removing the cloned repository files
          cd ..
          rm -rf bm_be
        EOF

