name: Deploy Nodejs to VPS Docker with Zero Downtime

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy back end to VPS with Zero Downtime
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        # SSH into VPS and deploy
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          
         
            git clone https://github.com/khoidang2110/baemin_be.git
          
          cd baemin_be || exit


          # Check if container bm_nest_8096 is running
          if docker ps --filter "name=bm_nest_8096" --format "{{.Names}}" | grep -q "bm_nest_8096"; then
            # If bm_nest_8096 is running, create bm_nest_8097 from image bm_be_8097
            # Build image bm_be_8097 if not already built
            docker build -t bm_be_8097 .
            
            # Run new container on port 8097
            docker run -e --restart=always -d -p 8097:8096 --name bm_nest_8097 bm_be_8097
            
            # Ensure the new container is running before stopping the old one
            sleep 5

            # Stop and remove the old container if it exists
            docker stop bm_nest_8096 || true
            docker rm bm_nest_8096 || true
          else
            # If bm_nest_8096 is not running, create bm_nest_8096 from image bm_be_8096
            # Build image bm_be_8096 if not already built
            docker build -t bm_be_8096 .
            
            # Run new container on port 8096
            docker run -e --restart=always -d -p 8096:8096 --name bm_nest_8096 bm_be_8096
            
             # Ensure the new container is running before stopping the old one
            sleep 5
            
            # Stop and remove the old container bm_nest_8097 if it exists
            docker stop bm_nest_8097 || true
            docker rm bm_nest_8097 || true
          fi

          # Clean up old images
          docker image prune -f

          # Delete the cloned repo if no longer needed
          cd ..
          rm -rf baemin_be
        EOF

